<a href="https://colab.research.google.com/github/ioshubham/SparkGCollab/blob/main/SarkInstallation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


# Run below commands to download the spark from apache website
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://apache.osuosl.org/spark/spark-3.4.2/spark-3.4.2-bin-hadoop3.tgz
!tar xf spark-3.4.2-bin-hadoop3.tgz
!pip install -q findspark


In [ ]:
!ls -a

.  ..  .config	sample_data  spark-3.4.2-bin-hadoop3  spark-3.4.2-bin-hadoop3.tgz


In [ ]:
# Run below command to setup environment for  the spark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.4.2-bin-hadoop3"


In [ ]:
#initialising Spark
import findspark
findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()
# Test the spark
df = spark.createDataFrame([{"hello": "world"} for x in range(1000)])

df.show(3, False)


ValueError: Couldn't find Spark, make sure SPARK_HOME env is set or Spark is in an expected location (e.g. from homebrew installation).

In [ ]:
# Check the pyspark version
import pyspark
print(pyspark.__version__)


3.4.2


In [ ]:
import findspark
findspark.init()

from pyspark.sql import SparkSession
import cv2
import numpy as np
from google.colab import drive




In [ ]:
spark = SparkSession.builder \
    .appName("VideoToFrames") \
    .getOrCreate()

In [ ]:
def extract_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    frames = []
    success, image = cap.read()
    while success:
        frames.append(image)
        success, image = cap.read()

    return frames

In [ ]:

video_path = r"/f/SparkIP.mp4"

if not os.path.isfile(video_path):
    raise ValueError("Invalid video path")

ValueError: Invalid video path

In [ ]:
frames_rdd = spark.sparkContext.parallelize(extract_frames(video_path))

first_frame = frames_rdd.first()
cv2.imshow('First Frame', first_frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

spark.stop()

ValueError: RDD is empty

In [ ]:
import findspark
findspark.init()

from pyspark.sql import SparkSession
import cv2
import numpy as np
from google.colab import drive

from google.colab import files

uploaded = files.upload()
for filename in uploaded.keys():
    print(f"Uploaded file: {filename}")


Saving SparkIP.mp4 to SparkIP.mp4
Uploaded file: SparkIP.mp4


In [ ]:
import cv2
import numpy as np

# Function to read video file and print all frames
def print_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("Error: Could not open video file.")
        return

    frame_count = 0
    while True:
        success, frame = cap.read()
        if not success:
            break

        print(f"Frame {frame_count}: {frame}")
        frame_count += 1

    cap.release()

# Path to the video file (update this with the filename you uploaded)
video_path = list(uploaded.keys())[0]

# Call the function to print all frames
print_frames(video_path)

Streaming output truncated to the last 5000 lines.
  [ 22  22 102]
  [ 22  22 102]]]
Frame 3064: [[[ 19  17  89]
  [ 19  17  89]
  [ 19  17  89]
  ...
  [231 234 255]
  [249 252 255]
  [243 246 255]]

 [[ 19  17  89]
  [ 19  17  89]
  [ 19  17  89]
  ...
  [234 237 255]
  [246 249 255]
  [239 242 253]]

 [[ 18  16  88]
  [ 18  16  88]
  [ 18  16  88]
  ...
  [232 238 255]
  [237 244 255]
  [238 245 255]]

 ...

 [[ 10  11  97]
  [ 10  11  97]
  [ 10  11  97]
  ...
  [ 23  22 100]
  [ 21  21 101]
  [ 21  21 101]]

 [[ 10  11  97]
  [ 10  11  97]
  [ 10  11  97]
  ...
  [ 23  22 100]
  [ 21  21 101]
  [ 21  21 101]]

 [[ 10  11  97]
  [ 10  11  97]
  [ 10  11  97]
  ...
  [ 24  23 101]
  [ 22  22 102]
  [ 22  22 102]]]
Frame 3065: [[[ 19  17  89]
  [ 19  17  89]
  [ 19  17  89]
  ...
  [231 234 255]
  [249 252 255]
  [243 246 255]]

 [[ 19  17  89]
  [ 19  17  89]
  [ 19  17  89]
  ...
  [234 237 255]
  [246 249 255]
  [239 242 253]]

 [[ 18  16  88]
  [ 18  16  88]
  [ 18  16  88]
  ...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

#!pip install sparkmagic

from pyspark.sql import SparkSession
import cv2
import numpy as np

Mounted at /content/drive
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.4/123.4 kB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.2/94.2 kB 13.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.1/221.1 kB 27.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━

In [ ]:
spark = SparkSession.builder \
    .appName("VideoToFrames") \
    .getOrCreate()

In [ ]:
video_path = '/content/drive/MyDrive/SparkIP.mp4'


In [ ]:
import cv2

# Function to read video file and extract frames
def extract_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    frames = []
    success, image = cap.read()
    while success:
        frames.append(image)
        success, image = cap.read()
    return frames

# Path to the video file
video_path = '/content/drive/MyDrive/SparkIP.mp4'

# Extract frames from video
frames = extract_frames(video_path)

# Print the number of frames extracted
print(f"Number of frames extracted: {len(frames)}")


In [ ]:
from google.colab import drive
drive.mount('/content/drive')
from pyspark.sql import SparkSession
import cv2
import numpy as np
spark = SparkSession.builder \
    .appName("VideoToFrames") \
    .getOrCreate()

Mounted at /content/drive


ModuleNotFoundError: No module named 'pyspark'

In [ ]:
#Env Setup

#!apt-get install openjdk-8-jdk-headless -qq > /dev/null
#!wget -q http://apache.osuosl.org/spark/spark-3.4.2/spark-3.4.2-bin-hadoop3.tgz
#!tar xf spark-3.4.2-bin-hadoop3.tgz
#!pip install -q findspark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.4.2-bin-hadoop3"

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
import findspark
findspark.init()
from pyspark.sql import SparkSession
import cv2
import numpy as np
spark = SparkSession.builder \
    .appName("VideoToFrames") \
    .getOrCreate()

Mounted at /content/drive


In [ ]:
!mkdir -p "/content/drive/My Drive/videoSnaps"

def FrameCapture(path):
    vidObj = cv2.VideoCapture(path)
    count = 0
    success = 1
    while success:
        success, image = vidObj.read()
        cv2.imwrite("/content/drive/My Drive/videoSnaps/frame%d.jpg" % count, image)
        count += 1

if __name__ == '__main__':
    video_path = '/content/drive/MyDrive/SparkIP.mp4'
    FrameCapture(video_path)

error: OpenCV(4.8.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'


In [ ]:
!mkdir -p "/content/drive/My Drive/videoSnapsUsingFPS"

def FrameCapture(path):
    vidObj = cv2.VideoCapture(path)
    count = 0

    fps = vidObj.get(cv2.CAP_PROP_FPS)

    interval = int(fps)

    success = 1

    while success:
        success, image = vidObj.read()

        if count % interval == 0:
            if success:
                cv2.imwrite("/content/drive/My Drive/videoSnapsUsingFPS/frame%d.jpg" % count, image)
            else:
                print("End of video reached")
        count += 1

if __name__ == '__main__':
    video_path = '/content/drive/MyDrive/SparkIP.mp4'
    FrameCapture(video_path)

In [ ]:
#Use this snippet to test

!mkdir -p "/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicate"


def FrameCapture(path):
    vidObj = cv2.VideoCapture(path)

    count = 0

    fps = vidObj.get(cv2.CAP_PROP_FPS)

    interval = int(fps)

    time_to_capture = fps

    captured_frames = []

    success = 1

    while success:
        success, image = vidObj.read()

        if count >= time_to_capture:
            if count not in captured_frames:
                if success:
                    cv2.imwrite("/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicate/frame%d.jpg" % count, image)
                else:
                    print("End of video reached")
                captured_frames.append(count)
            time_to_capture += fps
        count += 1

if __name__ == '__main__':
    video_path = '/content/drive/MyDrive/SparkIP.mp4'
    FrameCapture(video_path)

In [ ]:
!mkdir -p "/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicateHelp"
def frames_are_similar(frame1, frame2):
    # Convert frames to grayscale
    gray_frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    gray_frame2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

    # Compute the structural similarity index
    ssim = cv2.compare_ssim(gray_frame1, gray_frame2)

    # If SSIM is high, frames are similar (likely duplicates)
    return ssim > 0.95  # Adjust this threshold as needed

def FrameCapture(path):


    vidObj = cv2.VideoCapture(path)

    count = 0

    fps = vidObj.get(cv2.CAP_PROP_FPS)

    interval = int(fps)

    time_to_capture = fps

    success, prev_frame = vidObj.read()

    while success:

        success, current_frame = vidObj.read()

        if count >= time_to_capture:
            if success:
                if not frames_are_similar(prev_frame, current_frame):
                    cv2.imwrite("/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicateHelp/frame%d.jpg" % count, current_frame)
                    print("Frame %d saved to Google Drive" % count)

                    prev_frame = current_frame
                else:
                    print("Duplicate frame %d skipped" % count)
            else:
                print("End of video reached")
            time_to_capture += fps

        count += 1

if __name__ == '__main__':
    video_path = '/content/drive/MyDrive/SparkIP.mp4'
    FrameCapture(video_path)

AttributeError: module 'cv2' has no attribute 'compare_ssim'

In [ ]:
!mkdir -p "/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicateHelp"
def frames_are_similar(frame1, frame2):
    gray_frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    gray_frame2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

    # Compute Mean Squared Error (MSE)
    mse = np.mean((gray_frame1 - gray_frame2) ** 2)

    # If MSE is low, frames are similar (likely duplicates)
    return mse < 1000  # Adjust this threshold as needed

def FrameCapture(path):


    vidObj = cv2.VideoCapture(path)

    count = 0

    fps = vidObj.get(cv2.CAP_PROP_FPS)

    interval = int(fps)

    time_to_capture = 1000

    success, prev_frame = vidObj.read()

    while success:

        success, current_frame = vidObj.read()

        if count >= time_to_capture:
            if success:
                if not frames_are_similar(prev_frame, current_frame):
                    cv2.imwrite("/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicateHelp/frame%d.jpg" % count, current_frame)

                    prev_frame = current_frame
            else:
                print("End of video reached")
            time_to_capture += 1000

        count += 1

if __name__ == '__main__':
    video_path = '/content/drive/MyDrive/SparkIP.mp4'
    FrameCapture(video_path)

KeyboardInterrupt: 

In [ ]:
!mkdir -p "/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicateHelp"
import cv2

def frames_are_similar(frame1, frame2):
    # Convert frames to grayscale
    gray_frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
    gray_frame2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

    # Compute Mean Squared Error (MSE)
    mse = ((gray_frame1 - gray_frame2) ** 2).mean()

    # If MSE is low, frames are similar (likely duplicates)
    return mse < 1000  # Adjust this threshold as needed

def FrameCapture(path):
    vidObj = cv2.VideoCapture(path)

    count = 0

    success, prev_frame = vidObj.read()

    while success:
        success, current_frame = vidObj.read()

        if success:
            if not frames_are_similar(prev_frame, current_frame):
                cv2.imwrite(f"/content/drive/My Drive/videoSnapsUsingFPSRemoveDuplicateHelp/frame{count}.jpg", current_frame)

                prev_frame = current_frame

                count += 1

# Driver Code
if __name__ == '__main__':
    # Specify the path to your video file
    video_path = '/content/drive/MyDrive/SparkIP.mp4'

    # Calling the function to extract frames and save to Google Drive
    FrameCapture(video_path)


KeyboardInterrupt: 

In [ ]:
import cv2
import os
import time

video_path = '/content/drive/MyDrive/SparkIP.mp4'
output_dir = '/content/drive/MyDrive/videoSnapsUsingFPSRemoveDuplicateHelp'

try:
    # Create directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
except OSError:
    print('Error: Creating directory')

video = cv2.VideoCapture(video_path)

fps = int(video.get(cv2.CAP_PROP_FPS))
print('The FPS of the video is', fps)

time_start = time.time()
currentframe = 0
saved_frames = []

while True:
    ret, frame = video.read()

    if ret:
        # Check if the current frame is similar to any saved frame
        similar_to_saved = any(cv2.matchTemplate(frame, saved_frame, cv2.TM_CCOEFF_NORMED)[0][0] > 0.95 for saved_frame in saved_frames)

        if not similar_to_saved:

            frame_path = os.path.join(output_dir, f"frame{currentframe}.jpg")
            cv2.imwrite(frame_path, frame)
            saved_frames.append(frame)

        currentframe += 1
    else:
        break

time_end = time.time()
print('Total time taken:', time_end - time_start)
print('Total frames saved:', currentframe)

# Release all space and windows once done
video.release()
cv2.destroyAllWindows()


The FPS of the video is 29
Total time taken: 5993.9710574150085
Total frames saved: 3166


In [14]:
#!pip install pytesseract
#!apt-get install tesseract-ocr-eng

import os
import cv2
import pytesseract
from google.colab import drive

drive.mount('/content/drive')

frames_folder = '/content/drive/MyDrive/videoSnapsUsingFPSRemoveDuplicateHelp'

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 35 not upgraded.
Need to get 4,816 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1.1 [1,591 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1.1 [2,990 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr amd64 4.1.1-2.1build1 [236 kB]
Fetched 4,816 kB in 1s (8,111 kB/s)
Selecting previously unselected package tesseract-ocr-eng.
(Reading database ... 121749 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-eng_

In [15]:
pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'
ocr_config = r'--oem 3 --psm 6'

In [20]:
search_text = 'Oh what fun'

In [21]:
for filename in os.listdir(frames_folder):
    if filename.endswith('.jpg'):
        # Read frame
        frame_path = os.path.join(frames_folder, filename)
        frame = cv2.imread(frame_path)

        # Perform OCR
        text = pytesseract.image_to_string(frame, config=ocr_config)

        # Search for desired text
        if search_text in text:
            print(f'text found in frame: {filename}')

text found in frame: frame975.jpg
